spring:
    application:
        name: spring-practice-websocket-messaging-with-stomp
    
    threads:
        virtual:
            enabled: true

logging:
    level:
        org.springframework.messaging: TRACE
